apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokedex-app
  template:
    metadata:
      labels:
        app: pokedex-app
    spec:
      containers:
        - name: pokedex-app
          image: debray2523/pokedex-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "1.0"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
